sentence: subject verb object sentence.sh
	./sentence.sh

subject: subject.sh
	chmod +x subject.sh
	./subject.sh

verb: verb.sh
	chmod +x verb.sh
	./verb.sh

object: object.sh
	chmod object.sh
	./object.sh
